produtos/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from produtos import views

urlpatterns = [
    path('', views.homeProdutos, name='homeProdutos'),
    path('cadastrarProduto/', views.cadastrarProduto, name='cadastrarProduto'),
    path('EditarProduto/<int:produto_id>/', views.EditarProduto, name='Editar_Produto'),
    path('remover_Produto/<int:produto_id>/', views.remover_Produto, name='remover_Produto'),
    path('menuProdutos/', views.menuProdutos, name='menuProdutos'),
    path('detalhesProduto/<int:id>/', views.detalhesProduto, name='detalhesProduto'),
    ]

sistema_tk/urls.py
from django.contrib import admin
from django.urls import path, include
from usuarios.views import home, index_2
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('usuarios.urls')), #SERVE PARA TRANSFERIR AS URLS PARA URLS CRIADA NO APP USUARIOS
    path('inicio/', home),
    path('produtos/', include('produtos.urls')),
    path('login/', include('django.contrib.auth.urls'), name='login'),
] 


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

produtos/models.py
from django.db import models
from django.utils.crypto import get_random_string


class Produto(models.Model):
	STATUS_PROD = (
		(u'Disponivel', u'Disponivel'),
		(u'Indisponivel', u'Indisponivel'),
	)

	SIGLA_IDIOMA = (
		(u'pt_BR', u'pt_BR'),
		(u'en_US', u'en_US'),
	)

	ID = models.AutoField(primary_key=True)
	nome_produto = models.CharField(max_length=50)
	codigo_produto = models.IntegerField(unique=True)
	descricao_produto = models.CharField(max_length=500, blank=True)
	preco_produto = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True) #10 digitos com 2 casas decimais
	img_produto = models.FileField(upload_to='produtos/', null=True, blank=True) # Carregar arquivos
	status_produto = models.CharField(choices=STATUS_PROD ,max_length=15, default=0) # Pegar o status criado acima
	idioma = models.CharField(choices=SIGLA_IDIOMA ,max_length=10, default=0) # Pegas os idiomas criados acima

produtos/forms.py
from django import forms
from django.forms import ModelForm, fields
from .models import Produto

#PARA CADASTRAR USUARIO DO DJANGO PRECISA TER AS INFORMACOES ABAIXO
#PORQUE SAO AS INFORMACOES EXATAS DO DJANGO, NAO MUDAR, SE NAO VAI DAR ERRO

#ABAIXO VAI CADASTRAR USUARIO, MAS ELE NAO VAI TER ACESSO PAGINA DE ADMIN DO DJANGO
class ProdutoForm(forms.ModelForm):
    class Meta:
        model = Produto
        fields = [
        'ID',
        'codigo_produto',
        'nome_produto',
        'descricao_produto',
        'preco_produto',
        'status_produto',
        'img_produto',
        ]

        error_messagens = {
            "codigo_produto": {
                "required": "O Código do produto é obrigatório."
            },
            "nome_produto": {
                "required": "O Código do produto é obrigatório."
            },
            "descricao_produto": {
                "required": "Por favor, informe a descrição do produto."
            },
        }

            # SE FOR USAR DATAS, AQUI ESTÁ O MODELO PARA ERROS
            #"data_cadastro": {
                #"required": "A data de nascimento completo do visitante e obrigatorio para o resgistro.",
                #"invalid": "Por favor, informa um formato valido para a data de nascimento (DD/MM/AAA)"

produtos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.db import models, connection

from .models import Produto
from .forms import ProdutoForm
from django.contrib.auth.decorators import login_required

from .functions import excluirProduto


def homeProdutos(request):
	produto = Produto.objects.all().order_by('-codigo_produto')
	context = {
	'produtos': produto,
	}
	return render(request, "produtos.html", context)


@login_required
def cadastrarProduto(request):
	form = ProdutoForm(request.POST, request.FILES)

	if form.is_valid():
		form.save()
		messages.success(request, 'Produto cadastrado com sucesso')
		return redirect('/produtos/')
	else:
		print("Form não é valido")
		print(form.errors)

	context = {
	'form': form
	}

	return render(request, "cadastrarProduto.html", context)

@login_required
def EditarProduto(request, produto_id):
	produtos = get_object_or_404(Produto, ID=produto_id)
	form = ProdutoForm(request.POST , request.FILES, instance=produtos) #request.POST, request.FILES or None, instance = produto
	if form.is_valid():
		Pro_obj = form.save()
		Pro_obj.save()
		messages.success(request, 'Produto atualizado com sucesso')
		return redirect("/produtos/")
	else:
		print('Deu algum erro')
		print(form.errors)

	context = {
        "produtos": produtos,
        "form": form
        }
	return render(request,"editarProduto.html" ,context)

@login_required
def remover_Produto (request, produto_id):
    #produto = Produto.objects.get(ID=produto_id)
    deletar = excluirProduto(request, produto_id)
    return redirect('/produtos/')

def menuProdutos(request):
	produto = Produto.objects.all().order_by('-codigo_produto')
	context = {
	'produtos': produto,
	}
	return render(request, "menuProdutos.html", context)

def detalhesProduto(request, id):
	produto = Produto.objects.get(ID=id)
	context = {
	'produto': produto,
	}
	produto_ = produto.ID
	print(produto_)
	return render(request, "detalhesProduto.html", context)

produtos/templates/cadastrarProduto.html
{% extends 'base.html' %}

{% load bootstrap %}

{% block body %}

<div class="container col-md-5">
    <h1> Cadastrar Produtos </h1>
    <form method="POST" enctype="multipart/form-data" > 
        <!-- SEMPRE TER ESTE NOME = enctype="multipart/form-data"-->

        {% csrf_token %} <!--TOKEN DE SEGUANÇA DO PYTHON, TEM QUE TER NOS FORMULARIOS SEMPRE-->
        
        {{ form|bootstrap }}
        <button class="btn btn-primary col-md-3" type="submit"> Cadastrar </button>
        <br><br>
    </form>
</div>

{% endblock %}

produtos/templates/detalhesProduto.html
{% load static %}


<link rel="stylesheet" type="text/css" href="{% static 'css/estilo.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/all.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/js.js' %}">
<link href="https://use.fontawesome.com/releases/v5.0.11/css/all.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>


  
<!-- Modal -->


  <div class="modal-header">
    <h4 class="modal-title" id="exampleModalLabel">Nome: {{ produto.nome_produto }}</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <form method="GET" action="">

    <div class="modal-body text-center">
      {% if produto.img_produto %}
      <div class="imagem-carrinho">
          <img src="{{produto.img_produto.url}}" class="imagens-produtos">
      </div>
          {% else %}
      <div class="imagem-carrinho">
          <img  class="imagens-produtos" src="{% static 'imagens/sem-imagem.png'%}/">
      </div>
      {% endif %}
      <div class=" modal-body text-left">
        <p class="text-success"> <br>{{ produto.status_produto }} </p>
        <p><strong> Descrição: </strong><br>{{ produto.descricao_produto }} </p>
        <p><strong> Preço: </strong><br>R${{ produto.preco_produto }} </p>
      </div>
    </div>

    <div class="modal-footer">
      <button  type="button" class="btn btn-secondary text-white" data-dismiss="modal">Cancelar</button>
      <button type="button" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> Adcionar</button>
    </div>
  </form>

produtos/templates/editarProduto.html
{% extends 'base.html' %}

{% load bootstrap %}

{% load static %}

{% block body %}




        
<div class="container col-md-5 ">
    <h1> Editar informações do produto </h1>
    <form method="POST" enctype="multipart/form-data"> 
        
        {% csrf_token %}

        <div class="form-row">
            <div class="form-group col-md-4">
                <label class="control-label  " for="id_codigo_produto">Codigo produto</label>
                <input type="number" name="codigo_produto" value="{{produtos.codigo_produto}}" class=" form-control" required id="id_codigo_produto">
            </div>

            <div class="form-group col-md-8">
                <label class="control-label  " for="id_nome_produto">Nome produto</label>
                <input type="text" name="nome_produto" value="{{produtos.nome_produto}}" maxlength="50" class=" form-control" required id="id_nome_produto">     
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-12">
                <label class="control-label  " for="id_descricao_produto">Descricao produto</label>
                <textarea rows="3" type="text" name="descricao_produto" value="{{ produtos.descricao_produto }}" maxlength="500" class=" form-control" id="id_descricao_produto">{{ produtos.descricao_produto }}</textarea> 
            </div>
        </div>
        

        <div class="form-row">
            <div class="form-group col-md-4">
                {{form.preco_produto|bootstrap }}
            </div>

            <div class="form-group col-md-8">
                <label class="control-label  " for="id_status_produto">Status produto</label>
                <select name="status_produto" class=" form-control" id="id_status_produto"
                value="{{produtos.status_produto}}">
                    <option value="Disponivel">Disponivel</option>
                    <option value="Indisponivel">Indisponivel</option>
                </select>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-4">
                <label class="control-label " for="id_img_produto">Imagem do produto</label>
                <p><input type="file" name="img_produto" accept="image/*" id="id_img_produto"></p>
                {% if produtos.img_produto %}
                    <p><img width="180px" style="border-radius: 10px" src="{{ produtos.img_produto.url }}"></p>
                {% else %}
                    <p><img width="180px" style="border-radius: 10px" src="{% static 'imagens/sem-imagem.png'%}"></p>
                {% endif %}
            </div>
        </div>
        
        <div class="text-left">
            <button class="btn btn-primary" type="submit">
                <span class="text">Salvar Alterações</span>
            </button>
            <a href="{% url 'homeProdutos' %}" class="btn btn-secondary " type="button">
                <span class="text">Cancelar</span>
            </a>
        </div>
        
    </form>
    <br>
    <br>
    
</div>

{% endblock %}

produtos/templates/editarProduto1.html
{% extends 'base.html' %}

{% load bootstrap %}

{% load static %}

{% block body %}

<div class="container col-md-5">
    <h1> Editar informações do produto </h1>
    <form method="POST" enctype="multipart/form-data"  action="{% url 'salvarAlteracoesProduto' produto_id %}"> 
        <!-- SEMPRE TER ESTE NOME = enctype="multipart/form-data"-->

        {% csrf_token %}
        <!--TOKEN DE SEGUANÇA DO PYTHON, TEM QUE TER NOS FORMULARIOS SEMPRE-->

        <div class="form-group has-error">
            <label class="control-label  " for="id_codigo_produto">Codigo produto</label>
            <div class=" ">
                <input type="number" name="codigo_produto" class=" form-control" required id="id_codigo_produto" value="{{produtos.codigo_produto}}">
                <span class="help-block ">Este campo é obrigatório.</span>
            </div>    
        </div>

        <div class="form-group has-error">
            <label class="control-label  " for="id_nome_produto">Nome produto</label>
            <div class=" ">
                <input type="text" name="nome_produto" maxlength="50" class=" form-control" required id="id_nome_produto" value="{{produtos.nome_produto}}" >
                <span class="help-block ">Este campo é obrigatório.</span>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label  " for="id_descricao_produto">Descricao produto</label>
            <div class=" ">
                <input type="text" name="descricao_produto" maxlength="500" class=" form-control" id="id_descricao_produto" value="{{produtos.descricao_produto}}">  
            </div>
        </div>

        <div class="form-group">
            <label class="control-label  " for="id_preco_produto">Preco produto</label>
            <div class=" ">
                <input type="number" name="preco_produto" step="0.01" class=" form-control" id="id_preco_produto" value="{{produtos.preco_produto}}">     
            </div>
        </div>

        <div class="form-group has-error">
            <label class="control-label  " for="id_status_produto">Status produto</label>
            <div class=" ">
                <select name="status_produto" class=" form-control" id="id_status_produto" value="{{produtos.status_produto}}">
                    <option value="Disponivel">Disponivel</option>
                    <option value="Indisponivel">Indisponivel</option>
                </select>
                <span class="help-block ">Este campo é obrigatório.</span>
            </div>
        </div>

        <div class="form-group">    
            <label class="control-label  " for="id_img_produto">Img produto</label>
            <div class=" ">
                <input type="file" name="img_produto" accept="image/*" id="id_img_produto" value="{{produtos.img_produto.url}}">
            </div>
        </div>


        <button class="btn btn-primary col-md-3" type="submit"> Salvar alterações </button>
        <br><br>
        
    </form>
</div>

{% endblock %}

produtos/templates/menuProdutos.html
{% extends 'base.html' %} 

{% load bootstrap %} 

{% load static %} 

{% block body %}

<div class="container col-md-12 text-center">

        <h1>Produtos</h1>


    {% csrf_token %}
    <div class="form-row ">
        

        <div class="form-group col-md-10">
            {% if messages %}
            <ul class="message ">
                {% for message in messages %}
                <div class="alert alert-success col-md-4" role="alert">{{ message }}</div>
                {% endfor %}
            </ul>
            {% endif %}
        </div>
    </div>

    {% for produtos in produtos %} 
        {% if produtos.status_produto == 'Disponivel'  %} 
            {% if produtos.img_produto %}
                <div class="imagens-div">
                    <a href="{% url 'detalhesProduto' id=produtos.ID %}" data-toggle="modal" data-target="#mocal1"> <!-- data-toggle="modal" data-target="#exampleModal" -->
                        <img src="{{ produtos.img_produto.url }}" class="imagens-produtos">
                        <h3 class="nome-produto">{{produtos.nome_produto}} <br> R${{produtos.preco_produto}}</h3> 
                    </a>
                </div>

            {% else %}
                
                <div class="imagens-div">
                    <a href="{% url 'detalhesProduto' id=produtos.ID %}" data-toggle="modal" data-target="#mocal1">
                        <img src="{% static 'imagens/sem-imagem.png'%}/" class="imagens-produtos" >
                        <h3 class="nome-produto">{{produtos.nome_produto}} <br> R${{produtos.preco_produto}}</h3> 
                    </a>
                </div>
            {% endif %} 

        {% else %}

            {% if produtos.img_produto %}
                <div class="imagens-div">
                    <a href="{% url 'detalhesProduto' id=produtos.ID %}" data-toggle="modal" data-target="#mocal1" > <!-- data-toggle="modal" data-target="#exampleModal" -->
                        <img src="{{ produtos.img_produto.url }}" class="imagens-produtos">
                        <h3 class="nome-produto">{{produtos.nome_produto}} <br> R${{produtos.preco_produto}}</h3> 
                    </a>
                </div>

            {% else %}
                    
                <div class="imagens-div">
                    <a href="{% url 'detalhesProduto' id=produtos.ID %}" data-toggle="modal" data-target="#mocal1">
                        <img src="{% static 'imagens/sem-imagem.png'%}/" class="imagens-produtos" >
                        <h3 class="nome-produto">{{produtos.nome_produto}} <br> R${{produtos.preco_produto}}</h3> 
                    </a>
                </div>
            {% endif %} 

        {% endif %} 
    {% endfor %} 
</div>

<!-- Modal -->
<div class="modal fade" id="mocal1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">

        <!--
        AQUI FICA O CONTEUDO QUE VAI APARECER NO "MODAL"
        -->

        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
            <button type="button" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> Adcionar</button>
        </div>

        </div>
    </div>
</div>

{% endblock %}

produtos/templates/produtos.html
{% extends 'base.html' %}

{% load static %}

{% block body %}
<div class="container">
	
	{% csrf_token %}
	<div class="form-row">
		<div class="form-group">
			<h1>Produtos</h1>
		</div>

		<div class="form-group col-md-10">
			{% if messages %}
			<ul class="message ">
			    {% for message in messages %}
			    <div class="alert alert-success col-md-4" role="alert">{{ message }}</div>
			    {% endfor %}
			</ul>
			{% endif %}
		</div>
	</div>

	<div class="card-body">
	    <div class="table-responsive" style="border-radius:10px;">

			<table class="table table-striped table-light" style="border-radius:10px;">
			  <thead class="thead-dark">
			    <tr>
			      <th scope="col" >Código</th>
			      <th scope="col">Imagem</th>
			      <th scope="col">Produtos</th>
			      <th scope="col">Descrição</th>
			      <th scope="col" width="120px">Preços</th>
			      <th scope="col">Status</th>
			      {% if user.is_authenticated %}
			      	<th scope="col">Opções</th>
			      {% endif %}
			    </tr>
			  </thead>

			  <tbody>
			  	{% for produtos in produtos %}
				  

				  	{% if produtos.status_produto == 'Disponivel' %}
					    <tr>
					      <th scope="row">{{produtos.codigo_produto}}</th>
					      {% if produtos.img_produto %}
						  <td><img src="{{produtos.img_produto.url}}" class="thumbnail" width="80px"  height="80px"></td>
					      {% else %}
					      	<td><img width="80px" height="80px" class="thumbnail" src="{% static 'imagens/sem-imagem.png'%}/"></td>
					      {% endif %}
					      <td>{{produtos.nome_produto}}</td>
					      <td>{{produtos.descricao_produto}}</td>
					      <td>R$ {{produtos.preco_produto}}</td>
					      <td class="text-success"><strong>{{produtos.status_produto}}</strong></td>
					      {% if user.is_authenticated %}
					      	<td class="col-md-2">
					      		<a class="btn btn-primary" href="EditarProduto/{{produtos.ID}}"> Editar</a>
					      		<a class="btn btn-danger" href="{% url 'remover_Produto' produtos.ID %}" >Excluir</a> <!-- data-toggle="modal" data-target="#modal2"-->
					      	</td>
					      {% endif %}
					    </tr>

				    {% else %}

					    <tr class="bg-warning">
					      <th scope="row">{{produtos.codigo_produto}}</th>
					      {% if produtos.img_produto %}
					      	<td><img width="80px" height="80px" class="thumbnail" src="{{produtos.img_produto.url}}"></td>
					      {% else %}
					      	<td><img width="80px" height="80px" class="thumbnail" src="{% static 'imagens/sem-imagem.png'%}"></td>
					      {% endif %}
					      <td>{{produtos.nome_produto}}</td>
					      <td>{{produtos.descricao_produto}}</td>
					      <td>R$ {{produtos.preco_produto}}</td>
					      <td class="text-danger"><strong>{{produtos.status_produto}}</strong></td>
					      {% if user.is_authenticated %}
					      	<td class="col-md-2">
					      		<a class="btn btn-primary" href="EditarProduto/{{produtos.ID}}"> Editar</a>
					      		<a class="btn btn-danger" href="{% url 'remover_Produto' produtos.ID %}" >Excluir</a> <!--{% url 'remover_Produto' produtos.ID %}-->
								  <!-- data-toggle="modal" data-target="#modal2"-->
					      	</td>
					      {% endif %}
					    </tr>

				    {% endif %}

			    {% endfor %}
			  </tbody>
			</table>
		</div>
	</div>
</div>



<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">

         <!--
          AQUI FICA O CONTEUDO QUE VAI APARECER NO "MODAL"
        -->

        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
          <button type="button" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> Adcionar</button>
        </div>

      </div>
    </div>
  </div>

{% endblock %}

produtos/templates/remover_Produto.html
{% load static %}


<link rel="stylesheet" type="text/css" href="{% static 'css/estilo.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/all.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
<link href="https://use.fontawesome.com/releases/v5.0.11/css/all.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

<!-- Modal -->


  <div class="modal-header">
    <h4 class="modal-title" id="exampleModalLabel">Nome: {{ produto.nome_produto }}</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<form method="POST" action="">

  <div class="modal-body text-center">
    {% if produto.img_produto %}
    <div class="imagem-carrinho">
        <img src="{{produto.img_produto.url}}" class="imagens-produtos">
    </div>
        {% else %}
    <div class="imagem-carrinho">
        <img  class="imagens-produtos" src="{% static 'imagens/sem-imagem.png'%}/">
    </div>
    {% endif %}
    <div class=" modal-body text-left">
      <p class="text-success"> <br>{{ produto.status_produto }} </p>
      <p><strong> Descrição: </strong><br>{{ produto.descricao_produto }} </p>
      <p><strong> Preço: </strong><br>{{ produto.preco_produto }} </p>
    </div>
  </div>
  



  <div class="modal-footer">
    <button  type="button" class="btn btn-secondary text-white" data-dismiss="modal">Cancelar</button>
    <a type="button" href="{% url 'remover_Produto' produtos.ID %}" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> Adcionar</a>
  </div>
</form>