produtos/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from produtos import views

urlpatterns = [
    path('', views.homeProdutos, name='homeProdutos'),
    path('cadastrarProduto/', views.cadastrarProduto, name='cadastrarProduto'),
    path('EditarProduto/<int:produto_id>/', views.EditarProduto, name='Editar_Produto'),
    path('remover_Produto/<int:produto_id>/', views.remover_Produto, name='remover_Produto'),
    path('menuProdutos/', views.menuProdutos, name='menuProdutos'),
    path('detalhesProduto/<int:id>/', views.detalhesProduto, name='detalhesProduto'),
    ]

sistema_tk/urls.py
from django.contrib import admin
from django.urls import path, include
from usuarios.views import home, index_2
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('usuarios.urls')), #SERVE PARA TRANSFERIR AS URLS PARA URLS CRIADA NO APP USUARIOS
    path('inicio/', home),
    path('produtos/', include('produtos.urls')),
    path('login/', include('django.contrib.auth.urls'), name='login'),
] 


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from usuarios import views
from .classes import (
    password_reset, password_reset_done,
    password_reset_confirm, password_reset_complete
)

# AQUI VAI FICAR NOSSAS URLS, CADA UMA COM NAME PARA SE USADAS NOS TEMPLATES


urlpatterns = [
    path('', views.home, name="home"), #URL EM BRANCO, PAGINA INICIAL
    path('usuarios/', views.users, name="usuarios"),
    path('Cadastrar-Usuario/', views.cadastrar_usuario, name="cadastrarUsuario"),
    path('logout/', views.deslogar, name='deslogar'),
    path('alterarSenha/', views.alterar_senha, name="alterar_senha"),
    path('base2/', views.base_2, name='base2'), #Base de teste bootstrap
    path("resetPassword/", password_reset, name="resetPassword"),
    path("resetPassword/password_reset_done/", password_reset_done, name="password_reset_done"),
    path("resetPassword/password_reset_confirm/", password_reset_confirm, name="password_reset_confirm"),
    path("resetPassword/password_reset_complete/", password_reset_complete, name="password_reset_complete"),
    path("cadastrarPerfil/", views.cadastrar_perfil, name="cadastrar_perfil"),
    path("EditarPerfil/", views.EditarPerfil, name="EditarPerfil"),
    path("salvarAlteracoesUsuario/<slug:username>/", views.salvarAlteracoesUsuario, name="salvarAlteracoesUsuario"),
]

usuarios/models.py
from django.db import models

from django.contrib.auth.models import User
from django.db.models.signals import post_save

# QUI PODE SER ON DEVE CADASTRAR USUARIOS, PODE SER DIRETORES
class  UserProfile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    telefone = models.IntegerField(null=True, blank=True)
    endereco_completo = models.CharField(max_length=500, blank=True, null=True)
    idade = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return str(self.user)

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

usuarios/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm, fields

from .models import UserProfile

#PARA CADASTRAR USUARIO DO DJANGO PRECISA TER AS INFORMACOES ABAIXO
#PORQUE SAO AS INFORMACOES EXATAS DO DJANGO, NAO MUDAR, SE NAO VAI DAR ERRO

#ABAIXO VAI CADASTRAR USUARIO, MAS ELE NAO VAI TER ACESSO PAGINA DE ADMIN DO DJANGO
class Resgistrar_form(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        ]

class  UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = [
            'user',
            'telefone',
            'endereco_completo',
            'idade',
        ]

usuarios/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.contrib.auth.forms import  PasswordChangeForm
from django.contrib.auth import  update_session_auth_hash
from django.contrib import messages

from .forms import Resgistrar_form, UserProfileForm
from .models import UserProfile



# Create your views here.
#AQUI VAI FICAR AS VIEWS QUE VÃO SER CHAMADAS NO TEMPLATES
# Pagina inicial
def home (request):
    return render(request, 'index.html')

# pagina bootstrap de teste
def index_2 (request):
    return render(request, 'index2.html')

# pagina bootstrap de teste
def base_2 (request):
    return render(request, 'base2.html')

# pagina de usuario / teste
def users (request):
    
    if request.user.is_authenticated:
        user = request.user
        usuario = User.objects.all()
        perfil = UserProfile.objects.all()
    else:
        usuario = ""
        perfil = ""
    
    context = {
        "perfil": perfil,
        "usuario": usuario,
    }
    return render(request, 'users.html', context)

# Cadastrar novo usuario
def cadastrar_usuario (request):
    if request.method == 'POST':
        form = Resgistrar_form(request.POST)
        #Se o forma for valido ele salva e renderiza para pagina index
        if form.is_valid():
            form.save()
            return render(request, "index.html")
        # Se formulario nao for valido,vai voltar para pagina de cadastro
        else:
            form = Resgistrar_form()
            context = {
                'form': form,
            }
            return render(request, "cadastrarUsuario.html", context)
        #Se nao for request post vai voltar para formulario de cadastro também
    else:
        form = Resgistrar_form()
        context = {
            'form':form,
        }
        return render(request, "cadastrarUsuario.html", context)

#Deslogar / Sair
def deslogar(request):
    logout(request)
    return redirect("/inicio")

#Alterar senha
def alterar_senha(request):
    if request.method == "POST":
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            messages.success(request,"Senha alterada com sucesso!")
            update_session_auth_hash(request, form.user)
            
            return redirect('/inicio')

        else:
            messages.warning(request,"Erro ao alterar senha, ou senha incorreta!")
            return redirect("/alterarSenha")

    else:
        form = PasswordChangeForm(user=request.user)
    return render(request, 'alterarSenha.html', {'form_senha': form})


def cadastrar_perfil(request):
    form = UserProfileForm(request.POST)
    if form.is_valid():
        form.save()
        return redirect("/inicio/")
    else:
        print("Formulario não é valido")
        print(form.errors)
    
    context = {
        'form': form
    }
    return render(request, "cadastrarPerfil.html", context)


def EditarPerfil(request):
    if request.user.is_authenticated:
        user = request.user
        
        usuario = User.objects.get(username=request.user)
        #perfil = UserProfile.objects.get(user=user)
        perfil = UserProfile.objects.all()

        try:
            perfil = UserProfile.objects.all()
            for per in perfil:
                print('Deu tudo certo')
                print(per.user.id)
        except:
            print('Algo errado')
        
    else:
        usuario = ""
        perfil = ""
    
    context = {
        "perfil": perfil,
        "usuario": usuario,
    }
    return render(request, "EditarPerfil.html", context)


def salvarAlteracoesUsuario(request, username):
    usuario = User.objects.get(username=username)
    profile = UserProfile.objects.get(user=usuario.id)
    user = request.POST.get("user")
    first_name = request.POST.get("first_name")
    last_name = request.POST.get("last_name")
    email = request.POST.get("email")
    telefone = request.POST.get("telefone")
    endereco_completo = request.POST.get("endereco_completo")
    idade = request.POST.get("idade")

    usuario.username = username
    usuario.first_name = first_name
    usuario.last_name = last_name
    usuario.email = email
    usuario.save()

    profile.telefone = telefone
    profile.endereco_completo = endereco_completo
    profile.idade = idade
    profile.save()
    
    return redirect('/')

usuarios/templates/alterarSenha.html
{% extends 'base.html' %} 


{% load bootstrap %}

{% block body %}
<div class="container">
    <!-- MENSAGEM DE SUCESSO -->
    {% if messages %}
    <div class="alert alert-danger alert-dismissible fade show col-md-3"  role="alert">
        {% for mensagem in messages %}
        
        {{ mensagem }}
        
        {% endfor %}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %}

<!--**************************************************-->
    <h1>Alterar senha usuário</h1>
<form method="POST">
    {% csrf_token %}

    <div class="form-group col-md-4">
        {{form_senha.old_password.errors}}
        <!--<label>Senha antiga: </label>-->
        {{form_senha.old_password|bootstrap}}
    </div>

    <div class="form-group col-md-4">
        {{form_senha.new_password1.errors}}
        <!--<label>Nova senha: </label>-->
        {{form_senha.new_password1|bootstrap}}
    </div>

    <div class="form-group col-md-4">
        {{form_senha.new_password2.errors}}
        <!--<label>Confirmação de senha: </label>-->
        {{form_senha.new_password2|bootstrap}}
    </div>

    <div class="form-group ">
        <button type="submit" class="btn btn-primary"> ALterar senha</button>
        <br><br>
    </div>
</form>
</div>
{% endblock %}

usuarios/templates/cadastrarPerfil.html
{% extends 'base.html' %}

{% load bootstrap %}

{% block body %}
<div class="container col-md-5">
    <h1>Cadastrar Perfil do usuário</h1>
    <form method="POST">

        {% csrf_token %}

        {{ form|bootstrap }}

        <button type="submit" class="btn btn-primary"> Salvar alterações</button>
        <br><br>
    </form>
</div>
{% endblock %}

usuarios/templates/cadastrarUsuario.html
{% extends 'base.html' %}

{% load bootstrap %}

{% block body %}

<div class="container col-md-5">
    <h1> Cadastro de Usuario</h1>
    <form method="POST"  >
        {% csrf_token %} <!--TOKEN DE SEGUANÇA DO PYTHON, TEM QUE TER NOS FORMULARIOS SEMPRE-->
        
        {{ form|bootstrap }}
        <button class="btn btn-primary col-md-3" type="submit"> Cadastrar </button>
        <br><br>
    </form>
</div>

{% endblock %}

usuarios/templates/editarPerfil.html
{% extends 'base.html' %}

{% block body %}

<div class="container col-md-5 ">
    <h1 class="text-white">Editar Perfil do usuário</h1>
    <form method="POST" action="{% url 'salvarAlteracoesUsuario' usuario.username %}">

        {% csrf_token %}
        
    <p><label class="control-label text-white" for="id_user">Usuário</label>
    <select name="user" class=" form-control" required id="id_user">
      
          <option value="{{ usuario.id }}" selected>{{ usuario.username }} </option>
        
    </select></p>

    <div class="text-white">
    <p><label for="id_first_name">Primeiro nome:</label><input type="text" name="first_name" class=" form-control" id="id_first_name" value="{{ usuario.first_name }}" /></p>
    <p><label for="id_last_name">Último nome:</label><input type="text" name="last_name" class=" form-control" id="id_last_name" value="{{ usuario.last_name }}" /></p>
    <p><label for="id_email">E-mail:</label><input type="text" name="email" class=" form-control" id="id_email" value="{{ usuario.email }}" /></p>
    <p><label for="id_telefone">Telefone:</label><input type="number" name="telefone" class=" form-control" id="id_telefone" value="{{ perfil.telefone }}" /></p>
    <p><label for="id_endereco_completo">Endereço:</label><input type="text" name="endereco_completo"  maxlength="500" class=" form-control" id="id_endereco_completo"  value="{{ perfil.endereco_completo }}"/></p>
    <p><label for="id_idade"></label>Idade:<input type="number" name="idade" class=" form-control" id="id_idade" value="{{ profile.idade }}" /></p>
  </div>
          <button type="submit" class="btn btn-primary"> Salvar alterações</button></p>
          <br><br>
      </form>
</div>

<div class="container col-md-6">

<table class="table table-dark">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Nome</th>
        <th scope="col">Idade</th>
        <th scope="col">Telefone</th>
        <th scope="col">Endereço</th>
      </tr>
    </thead>
    {% for perfil in perfil %}
    <tbody>
      <tr>
        <th scope="row">1</th>
        <td><input type="text" name="user" class=" form-control" id="_id_user" value="{{ perfil.user }}" /></td>
        <td><input type="number" name="idade" class=" form-control" id="id_idade" value="{{ perfil.idade }}" /></td>
        <td><input type="number" name="telefone" class=" form-control" id="id_telefone" value="{{ perfil.telefone }}" /></td>
        <td><input type="text" name="endereco_completo"  maxlength="500" class=" form-control" id="id_endereco_completo"  value="{{ perfil.endereco_completo }}"/></td>
      </tr>
    </tbody>
    {% endfor %}
    
  </table>
</div>
<br><br>
{% endblock %}

usuarios/templates/index.html
{% extends 'base.html' %}


{% block body %}
<!-- JavaScript (Opcional) -->
<!-- jQuery primeiro, depois Popper.js, depois Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

<div class="container col-md-7">
    <!-- MENSAGEM DE SUCESSO -->
  {% if messages %}
  <div class="alert alert-success alert-dismissible fade show col-md-3"  role="alert">
      {% for mensagem in messages %}
      
        {{ mensagem }}
      
      {% endfor %}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
      </button>
  </div>
  {% endif %}
</div>

<!--**************************************************-->

<section id="home" class=" navbar-expand-md "><!--home -->
    <div class="row"><!--row -->
      <div class="col-md-12 capa">
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img class="img-slider" src="/static/imagens/1.jpg" alt="First slide">
            </div>
            <div class="carousel-item">
              <img class="img-slider" src="/static/imagens/2.jpg" alt="Second slide">
            </div>
            <div class="carousel-item">
              <img class="img-slider" src="/static/imagens/3.jpeg" alt="Second slide">
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
    </div><!--/row -->
</section><!--/home -->


<section id="recursos" class="caixa">
  <div class="container">
    <div class="row">
      <div class="col-md-4">

        <h2>TK Fácil</h2>
        <h3>Missão</h3>
        <p>Trabalhar de forma rápida, segura e com qualidade para entregar o fonecido.
        </p>

        <h3>Visão</h3>
        <p>A cada projeto feito +aprendizado e +confiança dos cleintes em nossos projetos.
        </p>

        <h3>Valores</h3>
        <p>Trabalhamos com confiança, e essa é a palavra chave para o sucesso.
        </p>

      </div>
      <div class="col-md-8">
        <div class="row rotacionar">
          <div class="col-md-6">
            <img src="../static/imagens/iphone1.png" class="img-fluid">
          </div>
          <div class="col-md-6">
            <img src="../static/imagens/iphone2.png" class="img-fluid">
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


<!-- JavaScript (Opcional) -->
<!-- jQuery primeiro, depois Popper.js, depois Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

{% endblock %}

usuarios/templates/message-alert.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>alert</title>
</head>
<body>
    
</body>
</html>

usuarios/templates/users.html
{% extends 'base.html' %}

{% load bootstrap %}

{% block body %}
<div class="container col-md-6">
    <h1 class="text-white">Usuários</h1>
    <p class="text-white">Usuarios marcados com cor <strong> azul </strong>é o ADM principal.</p>
    <form method="GET">
        {% csrf_token %}

<table class="table table-dark">
    <thead>
      <tr class="bg-danger">
        <th  scope="col">ID</th>
        <th scope="col">Usuário</th>
        <th scope="col">Idade</th>
        <th scope="col">Telefone</th>
        <th scope="col">Endereço</th>
      </tr>
    </thead>
    {% for perfil in perfil %}
    <tbody>
      <tr>
        <th scope="row">{{perfil.id}}</th>
        <td>{{ perfil.user }}</td>
        <td>{{ perfil.idade }}</td>
        <td>{{ perfil.telefone }}</td>
        <td>{{ perfil.endereco_completo }}</td>

      </tr>
    </tbody>
    {% endfor %}
    
    
    <thead>
        <tr class="bg-success" >
          <th  scope="col">ID</th>
          <th scope="col">Administrador</th>
          <th scope="col">Nome completo</th>
          <th scope="col">E-mail</th>
          <th scope="col"></th>
        </tr>
      </thead>

      {% for user in usuario %}
      <tbody>
        <tr>
          {% if user.username == 'lucasdev' %}

          <tr class="bg-info">
            <th scope="row">{{user.id}}</th>
            <td>{{ user.username }}</td>
            <td>{{ user.first_name }} {{ user.last_name }}</td>
            <td>{{ user.email }}</td>
            <td> </td>
          </tr>
          
          {% else %}

          <th scope="row"></th>
            <td></td>
            <td></td>
            <td></td>

          {% endif %}
        </tr>
      </tbody>

      {% endfor %}

  </table>
</div>
<br><br>
{% endblock %}